FROM node:20-alpine AS ui-builder

WORKDIR /ui-ngx

COPY ui-ngx/package.json ui-ngx/package-lock.json* ui-ngx/yarn.lock* ./
RUN npm install --legacy-peer-deps

COPY ui-ngx/ .
RUN npm run build:prod

FROM thingsboard/tb-node:latest

COPY --from=ui-builder /ui-ngx/target/generated-resources/public/ /usr/share/thingsboard/ui/
